version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/blok
    steps:
      - checkout
      - run: mvn -P ci clean package
      - run: ls
      - store_artifacts:
          path: NightShadeUHC/target/UHC.jar
          destination: artifacts
      - store_artifacts:
          path: NightShadeCore/target/Core.jar
          destination: artifacts
      - store_artifacts:
          path: NightShadeTournament/target/Tournament.jar
          destination: artifacts
      - store_artifacts:
          path: NightCheat/target/NightCheat.jar
          destination: artifacts
      - add_ssh_keys
      - deploy:
          name: Deploy to servers
          command: |
            ssh -o BatchMode=yes -o StrictHostKeyChecking=no dhillon@158.69.121.66 "uptime"
            scp NightShadeUHC/target/UHC.jar dhillon@158.69.121.66:~/minecraft/template/UHC.jar
            scp NightShadeCore/target/Core.jar dhillon@158.69.121.66:~/minecraft/template/Core.jar
            scp NightShadeTournament/target/Tournament.jar dhillon@158.69.121.66:~/minecraft/template/Tournament.jar
            scp NightCheat/target/NightCheat.jar dhillon@158.69.121.66:~/minecraft/template/NightCheat.jar
            echo "Finished uploading jars!"